name: mi_app
description: "A new Flutter project."
publish_to: 'none' # No publicar en pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.0.15
  csv: ^5.0.0
  path_provider: ^2.0.15
  permission_handler: ^11.3.1
  excel: ^2.0.4

  # Añadimos Hive y Hive Flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
